### ISSUE TITLE
enable navigation back

### ISSUE THREAD

**Issue by acuraintegurl** [canyaio/CanSeek#10]
<img width="1236" alt="screen shot 2018-07-25 at 4 13 09 pm" src="https://user-images.githubusercontent.com/39477899/43250588-0ea13eea-9101-11e8-82a5-d00f34a22a25.png">

# Description: 

User cannot go back 
# Acceptance criteria: 

Please include a back button on these pages

**Comment by thetadotonline** [comment]
User can use browser's back button
