### ISSUE TITLE
Jobs Card Style

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#18]
### Description

Minor spelling and grammatical issues on job cards as below
<img width="366" alt="screen shot 2018-07-31 at 10 46 10 am" src="https://user-images.githubusercontent.com/39213616/43430985-13651418-94af-11e8-9460-916feebf937d.png">

### Acceptance Criteria 

_from left to right, top to bottom_

<img width="473" alt="screen shot 2018-07-31 at 10 51 19 am" src="https://user-images.githubusercontent.com/39213616/43431111-b57b0c12-94af-11e8-97e4-2f095597387b.png">
   
- Span Tag Button height 25px

USD Contributed
- USD rounded whole dollars only (no decimals). Example "$45" instead of "$45.655"
- USD font-weight  800
- USD contributed font colour 4A4A4A
- Correct spelling of "Contributed" - replace first 'u' with an 'i'

Span num blue 
- font-weight 600  

Image Stretched (company logo)
Implement CSS rules on .card-img-top
- height: auto;
- max-width: 50%;
- padding: 15px 0 15px 0;

Job title  - title clamp1 
- font-weight 600
- colour 4A4A4A 
- text transform : capitalize

Company name (second pending)
- Use "company name" instead of "pending"
- font-weight 300

Location, Country or UTC missing
- Is this data collectected from Job poster in first release? If yes - surface here in same font format as "10 hours ago" nz-row

Job description
- use the below instead of "pending"
Here is the description of the person that we are looking for. This person needs to be sharp as a tack. If you or someone you know is looking for work with a brand that seeks to become the flagbearers ushering in new technology to the world. But no pressure though. 
- Font size 12px, line spacing 14 px

Can coin class="can-coin mr-8"
- Height and Width 35px 
- USD rounded whole dollars only (no decimals). Example "$1" instead of "$0.9133"
- USD font-weight  600
- Application Fee font-weight 300

Dots icon iconfont iconfont-ellipsis blue
_For 'All' page cards only_  - see note below about 'My posts page' use of ...
- Replace ant-dropdown-link ant-dropdown-trigger with "Refer Talent" button 
Refer talent specs
- Height 40px
- Width 155px
- Rounded corners
- Border 1px
- Border Colour 33CCFF
- Font colour 33CCFF
- Fill FFFFFF
Link to Job Preview Page (as below)

<img width="280" alt="screen shot 2018-07-31 at 11 25 07 am" src="https://user-images.githubusercontent.com/39213616/43432135-9f09d8a0-94b4-11e8-9233-ec6da67feb69.png">

_Card button For 'My posts page'_
- Use ant-dropdown-link ant-dropdown-trigger as exists currently 
- Dropdown to include; Edit, Delete and View Applicants

**Comment by jim-canya** [comment]
Styles are fixed.

Except for being in the "My Posts" and "My Referrals" tab, the card should be identical in terms of the functionalities.
