### ISSUE TITLE
Post a job - progress bar 

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#22]
### Description
Post a job progress bar minor updates to fonts and formatting
http://47.94.194.126/post?type=new
![canseek progress bar a](https://user-images.githubusercontent.com/39213616/43440080-4d8c31ba-94d9-11e8-8fc1-b6f5a1939619.PNG)

### Acceptance Criteria
![canseek progress bar b](https://user-images.githubusercontent.com/39213616/43440936-760347c0-94dc-11e8-9ec5-cd9f96ba05ec.PNG)
<img width="877" alt="screen shot 2018-08-02 at 3 36 22 pm" src="https://user-images.githubusercontent.com/39213616/43564377-d79b6a7e-9669-11e8-99aa-aefe4747a466.png">

- Add "Post a Job" as font header
- Remove "Identity Verify" as a step - there should be 3 steps only 
- Instead insert 1 line of text as subtitle to "post a Job" which reads "Before posting a job verify your identity"
- subtitle font colour 535353 font-size 18px font-weight 300px
- Correct spelling at "Job Infomation" to "Job Information"
- Title of each step - ie. "Job Information" etc to sit under number, not to right of.

Active step
- Text - ie "Identity Verify" Font colour 33ccff
- Numeral font colour FFFFFF
- font weight 400
- Leading line colour 33ccff

Secondary steps (number in circle) update to show 
- fill b7bbbd 
-font-weight 400 
-font colour FFFFFF

**Comment by jim-canya** [comment]
We think the current design makes more sense and since this change will take quite some time and cause delay in the delivery of the project, we'd like to keep the current design.
