### ISSUE TITLE
Post a Job: Metamask Tooltip at Verify Identity

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#30]
### Description 
No indication that login uses metamask app
<img width="1186" alt="screen shot 2018-08-02 at 12 10 01 pm" src="https://user-images.githubusercontent.com/39213616/43563069-9b06cb7c-9663-11e8-80ef-bee426ae7d12.png">

### Acceptance Criteria
- Add Login Tooltip: Notify user that "Login is via your metamask, you will receive notifications via your email."

**Comment by thetadotonline** [comment]
Pay is via your MetaMask, your email will prove your authority
