### ISSUE TITLE
Post a job: Salary Range

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#33]
### Description 
Split salary range into two inputs - $ minimum/annum and maximum/annum. 
+ Selecting "contract" "casual" changes prefill form data to $/hour

<img width="756" alt="screen shot 2018-08-02 at 3 30 41 pm" src="https://user-images.githubusercontent.com/39213616/43564206-0d4d7d0c-9669-11e8-84ec-4e5487c11d58.png">

### Acceptance Criteria
Two form fields in same line
+ Selecting "contract" "casual" changes prefill form data to $/hour

<img width="788" alt="screen shot 2018-08-02 at 3 26 29 pm" src="https://user-images.githubusercontent.com/39213616/43564164-d8582d86-9668-11e8-9bff-8e15ffd5c20f.png">

**Comment by thetadotonline** [comment]
Plain salary range allow people fill customize information, eg: 15k~30k$USD/month, etc.
