### ISSUE TITLE
Post a job: Need back button

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#34]
### Description
No back button is confusing for users
<img width="1041" alt="screen shot 2018-08-02 at 3 41 30 pm" src="https://user-images.githubusercontent.com/39213616/43564556-901e0ffc-966a-11e8-9058-1bcb4d02eb98.png">

### Acceptance Criteria
Use back button at top of screen as standard in CanApps
Colour 33ccff
<img width="1180" alt="screen shot 2018-08-02 at 3 42 17 pm" src="https://user-images.githubusercontent.com/39213616/43564572-ad3a9ab0-966a-11e8-8106-8fa134bd06a1.png">

**Comment by thetadotonline** [comment]
User can use browser's history back button or gesture to get back.

**Comment by thetadotonline** [comment]
In the page which has `steps component`, user are supposed to use `Back` button blow form (on the side of Next button) to get back step.
