### ISSUE TITLE
Post a Job: Set Fees and Reward - copy update

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#35]
### Description
<img width="1008" alt="screen shot 2018-08-02 at 3 43 26 pm" src="https://user-images.githubusercontent.com/39213616/43564609-d851ccf0-966a-11e8-9c25-8b12625f0b6e.png">

### Acceptance Criteria
Update copy to match below
- Replace "Honeypot" with "Initial Reward"
- Replace "This is your Company’s contribution to the initial honeypot to attract applicants." with "This is your Company’s contribution to the reward pool, paid to the successful talent."

- Replace "There is a 1% non-refundable fee sent to the CanYaDAO. You can cancel anytime for a full refund (minus fee). Cancelling will also refund all applicants. All Transactions on CanSeek are made in CAN tokens" with "Recomendation: We recommend an initial reward of 5% of the minimum salary range to attract talent. 
Eg. $100,000 salary = $5000 initial reward." **- Use font-size 10px, colour 33ccff** 

- Replace "Application Fee" with "Talent Application Fee"
- Replace  "This is the amount needed for talent hunters to join the pool."  with "This is the amount needed for talent hunters to join the pool, which adds to the total reward."
- Replace "There is a 1% non-refundable fee sent to the CanYaDAO. You can cancel anytime for a refund (minus fee)." with "Recomendation: We recommend an talent applicaton fee of between $10 - $50 USD. 
Higher fees typically result in less but higher quality applications." **- Use font-size 10px, colour 33ccff** 

- Add note
Note: A non refundable 1% fee is paid to the CanYaDAO.
You can cancel the job post at anytime for a refund.
All payments are held in CAN tokens.   

<img width="1167" alt="screen shot 2018-08-02 at 3 44 22 pm" src="https://user-images.githubusercontent.com/39213616/43564643-f792675a-966a-11e8-92c3-18b9e63af148.png">

**Comment by thetadotonline** [comment]
Since fee input must use can coin, `≈xxCAN` is no more needed.
