### ISSUE TITLE
Post a Job: Set Fees prefil form data

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#37]
### Description
Update pre fill form data to help the user make decisions
<img width="832" alt="screen shot 2018-08-02 at 3 54 09 pm" src="https://user-images.githubusercontent.com/39213616/43564995-62a285b0-966c-11e8-8c8f-85423731482f.png">

### Acceptance Criteria
- Replace "Minimum 500 CAN" with prefil 5% as described in issue #36 - OR - $1000
-Replace "Please Input" with "$10"
<img width="1167" alt="screen shot 2018-08-02 at 3 44 22 pm" src="https://user-images.githubusercontent.com/39213616/43565042-8f2e58e8-966c-11e8-98af-848459a5f6b1.png">

**Comment by thetadotonline** [comment]
CAN coin doesn't need prefill `$`

**Comment by keelymalady** [comment]
Yep, ok skip the $ - but please prefil a the numerical - "50"
