### ISSUE TITLE
Post a job: Review - buttons copy

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#41]
### Description
Update button copy
Remove "buy can" button from end of form - is now on header of every page
<img width="915" alt="screen shot 2018-08-02 at 4 05 29 pm" src="https://user-images.githubusercontent.com/39213616/43565585-8f41342a-966e-11e8-9bfb-d2bc8eec1938.png">

### Acceptance Criteria
Replace "Submit" with "Pay and Post Job"
Add Cancel button on left hand side
<img width="980" alt="screen shot 2018-08-02 at 4 10 35 pm" src="https://user-images.githubusercontent.com/39213616/43565599-a38d6ff2-966e-11e8-946c-4ad6796289fc.png">

**Comment by thetadotonline** [comment]
1. Since `buy can` button is not necessary in production environment, and it will halt the page if user doesn't start MetaMask, so i move it to the place where it needed.
2. User can click `Back` button or `CanSeek` logo to give up posting a job.
