### ISSUE TITLE
Post Job - Success Despite no Payment/Metamask connection

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#43]
### Description
As per #40 I was able to proceed and 'submit' or post job, despite no payment or metamask address
After selecting 'pay and post job' (previously called submit) button - 'view details' appeared and I was able to view a preview of my pending job without paying anything to CanSeek.
The good news - pay and post job remained in 'processing' mode with spinning wheel, but I shouldnt have been able to preview without paying?

<img width="662" alt="screen shot 2018-08-02 at 4 25 15 pm" src="https://user-images.githubusercontent.com/39213616/43566157-cebcc694-9670-11e8-895e-cac2d016b3fb.png">

<img width="1264" alt="screen shot 2018-08-02 at 4 27 09 pm" src="https://user-images.githubusercontent.com/39213616/43566199-fb32467c-9670-11e8-8b70-f95b87238872.png">

<img width="1219" alt="screen shot 2018-08-02 at 4 29 00 pm" src="https://user-images.githubusercontent.com/39213616/43566265-32e99c64-9671-11e8-988b-aafac4962784.png">

### Acceptance Criteria
- Replace "pending" status with "Incomplete" to more accurately reflect the status
- In the case that a transaction doesn't proceed because the MetaMask address is missing, Add a line of text that asks the user "To complete this transaction, open your MetaMask wallet" - **help wanted** for technical solution this point to help the user get their address

**Comment by jim-canya** [comment]
Fixed. There are actually three pending statuses, pending to add, pending to cancel, and pending to close. So pending is the better wording.
