### ISSUE TITLE
View Job Post - Information Formatting

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#44]
### Description
Format position type, salary and location 

<img width="723" alt="screen shot 2018-08-02 at 4 55 41 pm" src="https://user-images.githubusercontent.com/39213616/43567409-fe91e742-9674-11e8-95bf-a79e2e139bb1.png">

### Acceptance Criteria
Minimum acceptance 

- seperate onto 3 lines
- add labels "position type" "salary range" "location" - prefer labels in font-weight:500
- text-transform: capitalise
- add $ to salary

<img width="685" alt="screen shot 2018-08-02 at 5 05 18 pm" src="https://user-images.githubusercontent.com/39213616/43567815-46f7214a-9676-11e8-88db-9e0c57086367.png">

V2 Acceptance Criteria - design team to create icons to reduce text (backlog for now)

**Comment by Aurumsy** [comment]
Salary Range is put in as pure strings, this enable users to specify salary in different currencies. So the dollar sign should be put in by the users themselves?
