### ISSUE TITLE
Post a Job: Salary Range is free-text

### ISSUE THREAD

**Issue by jpthor** [canyaio/CanSeek#49]
home -> post a job -> add details

Current
Salary Range is free-text

Desired
Salary Range should be two numbers (minimum) and (maximum)

**Comment by jim-canya** [comment]
This is designed deliberately for multi-currency or inputting "flexible" etc options.

**Comment by jpthor** [comment]
The inputs should be able to take anything, but users should be able to set a range. It is an optional field

**Comment by keelymalady** [comment]
Agree that it needs to be flexible, but we should be encouraging a range as per industry standards in recruiting. 

V1 Placeholder test suggests range as per issue #60 

V2 two form fields to capture range As per issue #33 
![image](https://user-images.githubusercontent.com/39213616/43749721-980e714e-9a38-11e8-96ec-211ea82bf453.png)

**Comment by thetadotonline** [comment]
「 will this number be captured using the currency selected in the header? Or should we be encouraging the user to clarify which currency the salary is in manually」

Answer: Both can be implemented, it depends on your requirement.

Preview below:

<img width="710" alt="2018-08-07 6 14 06" src="https://user-images.githubusercontent.com/39830932/43770556-51556078-9a6f-11e8-98b7-83f35bea808c.png">
<img width="717" alt="2018-08-07 6 17 53" src="https://user-images.githubusercontent.com/39830932/43770563-58b0aa58-9a6f-11e8-805e-10b53f086e93.png">

**Comment by keelymalady** [comment]
@xinjie I cant replicate this - has it been deployed?

![image](https://user-images.githubusercontent.com/39213616/43882152-03fb70ea-9bf2-11e8-839c-a6e3e412020d.png)

**Comment by jpthor** [comment]
Keely and I discussed this.

For the Salary Min/Max:

[salaryMinimum] <CURRENCY> [salaryMaximum] <CURRENCY>
Where <CURRENCY> label is set by header dropdown.

For Fees:

Reward Fee:
[feeReward] <CURRENCY>

Application Fee:
[feeApplication] <CURRENCY>
Where <CURRENCY> label is set by header dropdown.

but if `[salaryMinimum]` then 
[feeReward] = 0.05 * [salaryMinimum]
Where [numberFee] is default 10;
