### ISSUE TITLE
Edit Job Post: Unable to Edit or Cancel Posts

### ISSUE THREAD

**Issue by jpthor** [canyaio/CanSeek#52]
Post a job -> tried to pay -> Home screen -> "my posts" -> Update button

Current
"Post didn't exist"

Desired
Take me to edit screen

**Comment by keelymalady** [comment]
Description
As per Zeplin flow zpl.io/2j4xjep submitted July - incorporate ability to edit an existing post

Acceptance Criteria
- "Edit job" page as per zeplin file
- Prefill form fields with text submitted by user during 'post a job' process - do not leave blank, or use as placeholder text. Needs to be editable.

<img width="535" alt="screen shot 2018-08-07 at 11 44 11 am" src="https://user-images.githubusercontent.com/39213616/43749513-c8cfc446-9a37-11e8-8704-0dde9d0ba60f.png">

**Comment by keelymalady** [comment]
![image](https://user-images.githubusercontent.com/39213616/43880019-0af13f5e-9bea-11e8-910f-841d1aa6c60a.png)
