### ISSUE TITLE
Header: Connection to MetaMask

### ISSUE THREAD

**Issue by jpthor** [canyaio/CanSeek#54]
Current
- Existing header format doesnt help user understand if they are successfully connected to metamask
- CanApps button link doesnt work
<img width="1201" alt="screen shot 2018-08-07 at 10 41 48 am" src="https://user-images.githubusercontent.com/39213616/43747640-85b737ba-9a2e-11e8-9e66-53b8a79d8fbc.png">

Desired
- Integrate the header from CANWork that has profile button as well as network connectivity widget.
- CanApps link to https://www.canwork.io/tools

**Comment by acuraintegurl** [comment]
## New Header format

- If using a browser that does not support metamask (eg. safari)

<img width="1637" alt="screen shot 2018-08-06 at 4 20 46 pm" src="https://user-images.githubusercontent.com/39477899/43700252-49a0ee86-9995-11e8-92cb-39d4ff55402e.png">

- If using a browser that supports metamask, but is not signed in

<img width="1634" alt="screen shot 2018-08-06 at 4 21 01 pm" src="https://user-images.githubusercontent.com/39477899/43700267-5ab4898a-9995-11e8-99d1-a1e7b9566077.png">

**Comment by wie-canya** [comment]
I've integrated this widget to CanWork. I'll help in integrating this to CanSeek.

**Comment by keelymalady** [comment]
@wie-canya to intergrate

**Comment by keelymalady** [comment]
@thetadotonline I can't see that the "JOIN" button and feature has been implemented

Current state
<img width="1246" alt="screen shot 2018-08-15 at 11 28 51 am" src="https://user-images.githubusercontent.com/39213616/44127049-c2913e82-a07e-11e8-8df3-07b99b5c00ad.png">

Acceptance criteria as per @acuraintegurl comment above

Let me know if you need more information from @wie-canya or others to intergrate
<img width="1246" alt="screen shot 2018-08-15 at 11 28 51 am" src="https://user-images.githubusercontent.com/39213616/44127067-e1815a34-a07e-11e8-8e56-834e45090167.png">

**Comment by thetadotonline** [comment]
I missed the "JOIN" button, and will fix later

**Comment by keelymalady** [comment]
Ok great @thetadotonline keep this open until fixed
