### ISSUE TITLE
Home page: Don't allow "pending" posts to show publically

### ISSUE THREAD

**Issue by acuraintegurl** [canyaio/CanSeek#58]
Hide pending posts as they can't be actioned. 
We should hide ‘pending’ and ‘cancelled’ jobs, show only open and closed jobs.

**Comment by keelymalady** [comment]
(?) add tooltip next to status

**Comment by thetadotonline** [comment]
pending action: `edit` and `view applicants` by owner.
cancelled action: `get refund` and `view applicants` by owner.
