### ISSUE TITLE
Footer: Social Links 

### ISSUE THREAD

**Issue by acuraintegurl** [canyaio/CanSeek#59]
There are no links to social on the footer. They could be hidden due to the site not having fontawesome. Check canwork.io's footer for reference.

**Comment by acuraintegurl** [comment]
<img width="1668" alt="screen shot 2018-08-06 at 5 44 58 pm" src="https://user-images.githubusercontent.com/39477899/43703574-7adee600-99a0-11e8-91d6-77809147030a.png">

**Comment by keelymalady** [comment]
@wie-canya Did you have a standardised footer already set up?

**Comment by keelymalady** [comment]
<img width="1350" alt="screen shot 2018-08-07 at 11 03 19 am" src="https://user-images.githubusercontent.com/39213616/43748187-8e867e98-9a31-11e8-957d-c43456f58428.png">

**Comment by wie-canya** [comment]
I'll work on it
