### ISSUE TITLE
Post a Job/Edit: Job Location and Allow Remote Working

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#65]
### Description
<img width="990" alt="screen shot 2018-08-07 at 2 25 46 pm" src="https://user-images.githubusercontent.com/39213616/43754365-ce0eb8e8-9a4d-11e8-92b4-f6a12e24fa9d.png">

### Acceptance Criteria### 
- Add "Allow Remote Working" as a label below 'job location'
- Add two button selector 'yes' and 'no' only 1 can be true
- Update placeholder copy in 'job location' Location, Country or Timezone UTC
<img width="584" alt="screen shot 2018-08-07 at 2 33 54 pm" src="https://user-images.githubusercontent.com/39213616/43754590-f7928342-9a4e-11e8-9393-13124aae8ce5.png">

V2 Make location a *required question, but allow job poster to retract Country information from Job post, just showing Timezone data as above

**Comment by thetadotonline** [comment]
Could you make it more clearly about V2?

**Comment by keelymalady** [comment]
V2 isn't required to be built at this time, but; 
In the future, the Job Location is a *mandatory question, but, being empathetic to security-cautious users, who have expressed a preference to only disclose their timezone, not their physical location. 

This insight was determined during research for CanWork and will be implemented there as well in time.

An example;
As a job poster, I input

Melbourne, Australia

as the job location, but I want to allow remote work and


TBC

**Comment by keelymalady** [comment]
V2 will be moved to seperate issue
