### ISSUE TITLE
Payment: Reject Transaction

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#68]
### Description
Reject a transaction in MetaMask > redirected to MetaMask home page

### Acceptance Criteria
Reject a transaction in MetaMask > redirected to page submit payment page in CanSeek
MVP Redirected to CanSeek homepage

**Comment by thetadotonline** [comment]
I didn't get your point, can you make it more detailed and clear?

**Comment by keelymalady** [comment]
### Issue observed
If for some reason as user needs to reject a transaction in metamask, they were redirected away from canseek and to the metamask website.

### Testing @wie-canya  encountered this specific bug - and tested it in a few instances. The way the code is written, if there is any error during any metamask transaction (by user or by metamask), the code redirects the user to the metamask home page. This is confusing for the user.

### Acceptance criteria:
An error in metamask should raise an error message on canseek, and allow the user to find out what is happening from canseek's perspective. If needed it can allow the user to open another window with the metamask support or home page, but the user should not be directed away from canseek.

**Comment by keelymalady** [comment]
@wie-canya can you explain better?

**Comment by thetadotonline** [comment]
Can you record a video for this case?
