### ISSUE TITLE
Post a Job: Pay and Submit copy

### ISSUE THREAD

**Issue by keelymalady** [canyaio/CanSeek#69]
### Description
Below 'Pay and Submit' we have this explanation of the MetaMask flow that will follow pressing the button.
"To complete creating the job post, you must submit TWO metamask pop-up confirmations. Make sure you have enough ETH to cover the transaction fees and check the translation status in Metamask."
<img width="1096" alt="screen shot 2018-08-07 at 3 17 28 pm" src="https://user-images.githubusercontent.com/39213616/43756358-968f1e9e-9a57-11e8-9156-294016d1c807.png">

@jim-canya can you explain what the two transactions are for? I will then update the copy to make this more user friendly. 

### Acceptance Criteria
TBC

**Comment by keelymalady** [comment]
@thetadotonline can you be more specific about the details of your TBC

**Comment by keelymalady** [comment]
@jim-canya can you explain what the two transactions are for? I will then update the copy to make this more user friendly.

**Comment by keelymalady** [comment]
1st transaction is to the escrow contract
2nd transaction is for paying the contribution fee

**Comment by thetadotonline** [comment]
is it really need to tell user what's the two click for?
