### ISSUE TITLE
Update mandatory fields

### ISSUE THREAD

**Issue by acuraintegurl** [canyaio/CanSeek#7]
<img width="726" alt="screen shot 2018-07-25 at 4 15 21 pm" src="https://user-images.githubusercontent.com/39477899/43250317-6df01ba6-9100-11e8-9dce-b5a8c9f1872d.png">

# Description: 

Company website not mandatory. This would help to stop fraudulent posts.

# Acceptance criteria: 

Make website mandatory

**Comment by thetadotonline** [comment]
Since company's website doesn't equal to email suffix some times,  i finally use email verify instead to stop fraudulent post.
