### ISSUE TITLE
Refer Talent Button hangs at "application contribution" stage.

### ISSUE THREAD

**Issue by kaiansaari** [canyaio/CanSeek#75]
On ethereum mainnet, not getting any metamask popup when contributing.

![image](https://user-images.githubusercontent.com/26814804/43932774-55fa45fa-9c89-11e8-84f0-851a90c277e6.png)

**Comment by thetadotonline** [comment]
Please test on Ropsten first.Because there are some issues todo, i didn't deploy the latest website on mainnet.
